BASE:
- ''
TOOLBOX_MODE: train_and_test
TRAIN:
  BATCH_SIZE: 64
  EPOCHS: 30
  LR: 1e-3
  MODEL_FILE_NAME: UBFCPHYS_RTMRCPNet_single_left_cheek
  PLOT_LOSSES_AND_LR: true
  DATA:
    FS: 30
    DATASET: UBFC-PHYS-STRESS-RGB
    DO_PREPROCESS: false
    DATA_FORMAT: KTC
    DATA_PATH: RawData
    CACHED_PATH: PreprocessedData
    EXP_DATA_NAME: UBFCPHYS_StressRGB_ROI5_Chunk160
    BEGIN: 0.0
    END: 0.7
    PREPROCESS:
      DATA_TYPE:
      - Raw
      LABEL_TYPE: Stress
      DO_CHUNK: true
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: true
        BACKEND: HC
        USE_LARGE_FACE_BOX: true
        LARGE_BOX_COEF: 1.3
        DETECTION:
          DO_DYNAMIC_DETECTION: false
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: false
      RESIZE:
        W: 128
        H: 128
VALID:
  DATA:
    FS: 30
    DATASET: UBFC-PHYS-STRESS-RGB
    DO_PREPROCESS: false
    DATA_FORMAT: KTC
    DATA_PATH: RawData
    CACHED_PATH: PreprocessedData
    EXP_DATA_NAME: UBFCPHYS_StressRGB_ROI5_Chunk160
    BEGIN: 0.7
    END: 0.85
    PREPROCESS:
      DATA_TYPE:
      - Raw
      LABEL_TYPE: Stress
      DO_CHUNK: true
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: true
        BACKEND: HC
        USE_LARGE_FACE_BOX: true
        LARGE_BOX_COEF: 1.3
        DETECTION:
          DO_DYNAMIC_DETECTION: false
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: false
      RESIZE:
        W: 128
        H: 128
TEST:
  METRICS:
  - ACC
  - Precision
  - Recall
  - F1
  - AUC
  USE_LAST_EPOCH: false
  DATA:
    FS: 30
    DATASET: UBFC-PHYS-STRESS-RGB
    DO_PREPROCESS: false
    DATA_FORMAT: KTC
    DATA_PATH: RawData
    CACHED_PATH: PreprocessedData
    EXP_DATA_NAME: UBFCPHYS_StressRGB_ROI5_Chunk160
    BEGIN: 0.85
    END: 1.0
    PREPROCESS:
      DATA_TYPE:
      - Raw
      LABEL_TYPE: Stress
      DO_CHUNK: true
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: true
        BACKEND: HC
        USE_LARGE_FACE_BOX: true
        LARGE_BOX_COEF: 1.3
        DETECTION:
          DO_DYNAMIC_DETECTION: false
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: false
      RESIZE:
        W: 128
        H: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  NAME: RTMRCPNet
  RTMRCPNET:
    NUM_ROIS: 5
    INPUT_CHANNELS: 3
    HIDDEN_DIM: 128
    NUM_CLASSES: 2
    DROPOUT: 0.5
    USE_TEMPORAL_ATTENTION: true
    USE_REGION_ATTENTION: false
    USE_REGION_RESIDUAL: false
    DATA_VARIANT: single_left_cheek
    ARCHITECTURE: rtmrcpnet
INFERENCE:
  BATCH_SIZE: 64
  MODEL_PATH: ''
